#!/usr/bin/ruby
# vim: noai:ts=4:sw=4
#
#  Copyright (C) 2010-2017 by Luiz Angelo Daros de Luca
#    luizluca@gmail.com
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    Created on 2010-08-10
#
# Changelog:
#
# * 2026-10-01
# - Use mutex to isolate concurrent access to connections
#
# * 2017-03-17
# - Add support for http proxy authentication using auto-detect support
#
# * 2010-09-01
# - Add TCP keepalive flags for local socket (thanks Jan Adámek)
# - Increased local buffer to 640k
# - Fixed sync problem with stdin/out when using as ProxyCommand inside ssh config
# - Reconnection on client-webrick disconnection
# - Fixed proxy absence
# - Specified webrick timeout (10m)
# - Treated more signals
# - Divide connection (open, read, write)
#
#
#################
#
# Port Forward client/server over HTTP
#
#################

class String
    def strip_heredoc
        min = scan(/^[ \t]*(?=\S)/).min
        if min == nil
            indent=0
        else
            indent=min.size
        end
        gsub(/^[ \t]{#{indent}}/, '')
    end
end

case ARGV.size
    when 2
        server=true
        location=ARGV[1]
     when 4
        server=false
        url=ARGV[1]
        remote_host=ARGV[2]
        remote_port=ARGV[3].to_i
    else
    $stderr.puts <<-EOF.strip_heredoc
	Use as server:
	#$0 localPort bridgeLocation
	
	Use as client:
	#$0 localPort|STDIN bridgeURL remoteAddress remotePort
	
	Ex:
	bridge$ #$0 8080 /bridge
	
	client$ #$0 8022 http://mybridge:8080/bridge remoteServer 22
	client$ ssh localhost -p 8022
	EOF
    exit
end

localPort=ARGV[0]

require 'socket'
require 'thread'
Thread.abort_on_exception = true

MAXBUF=1024*640 # 640k
READ_TIMEOUT=60
if server

    begin
        require 'webrick'
    rescue LoadError
        # ==========================================
        # Fake WEBrick
        # ==========================================
        module WEBrick
            module HTTPServlet
                class AbstractServlet
                end
            end

            class HTTPRequest
                attr_reader :method, :path, :version, :headers, :body, :peeraddr

                def initialize(method, path, version, headers, body, peeraddr)
                    @method, @path, @version = method, path, version
                    @headers, @body, @peeraddr = headers, body, peeraddr
                end
            end

            class HTTPResponse
                attr_accessor :status, :body
                attr_reader :headers

                def initialize
                    @status = 200
                    @headers = {}
                    @body = ""
                end

                def []=(key, val)
                    @headers[key] = val
                end
            end

            class HTTPServer
                STATUS_NAMES = {
                    200 => "OK", 201 => "Created", 204 => "No Content",
                    404 => "Not Found", 405 => "Method Not Allowed",
                    406 => "Not Acceptable", 410 => "Gone", 500 => "Internal Error"
                }

                def initialize(options = {})
                    @port = options[:Port] || 8080
                    @mounts = {}
                end

                def mount(path, servlet_class)
                    @mounts[path] = servlet_class.new
                end

                def start
                    @servers = Socket.tcp_server_sockets(@port).map do |sock|
                        sock.autoclose = false
                        TCPServer.for_fd(sock.fileno)
                    end

                    now = Time.now.strftime("%Y-%m-%d %H:%M:%S")
                    $stderr.puts "[#{now}] INFO  (Mini)WEBrick 1.0.0"
                    $stderr.puts "[#{now}] INFO  ruby #{RUBY_VERSION} (#{RUBY_RELEASE_DATE}) [#{RUBY_PLATFORM}]"
                    $stderr.puts "[#{now}] INFO  WEBrick::HTTPServer#start: pid=#{Process.pid} port=#{@port}"

                    loop do
                        reads, = IO.select(@servers)
                        reads.each do |server|
                            begin
                                client = server.accept
                            rescue IOError
                                next
                            end

                            Thread.new(client) { |c| handle_client(c) }
                        end
                    end
                end

                def shutdown
                    @server.close unless @server.closed?
                end

                private

                def handle_client(c)
                    loop do
                        req_line = c.gets
                        break if req_line.nil? || req_line.strip.empty?

                        method, raw_path, version = req_line.strip.split(/\s+/, 3)

                        if method.nil? || raw_path.nil? || version.nil?
                            c.print "HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n"
                            break
                        end

                        require 'uri' unless defined?(URI)
                        begin
                            parsed_uri = URI.parse(raw_path)
                            path = URI.decode_www_form_component(parsed_uri.path)
                        rescue URI::InvalidURIError
                            c.print "HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n"
                            break
                        end

                        headers = {}
                        while (line = c.gets) && line != "\r\n"
                            key, value = line.split(/:\s*/, 2)
                            headers[key.downcase] = value.strip if key && value
                        end

                        body = ""
                        if headers['content-length']
                            len = headers['content-length'].to_i
                            body = c.read(len) if len > 0
                        end

                        req = HTTPRequest.new(method, path, version, headers, body, c.peeraddr)
                        res = HTTPResponse.new

                        servlet = @mounts.find { |m_path, _| path.start_with?(m_path) }&.last

                        if servlet
                            begin
                                case method
                                when 'GET'    then servlet.do_GET(req, res)
                                when 'POST'   then servlet.do_POST(req, res)
                                when 'PUT'    then servlet.do_PUT(req, res)
                                when 'DELETE' then servlet.do_DELETE(req, res)
                                else res.status = 405
                                end
                            rescue => e
                                res.status = 500
                                $stderr.puts "Servlet Error: #{e.message}"
                            end
                        else
                            res.status = 404
                        end

                        status_msg = STATUS_NAMES[res.status] || "Unknown"
                        c.print "HTTP/1.1 #{res.status} #{status_msg}\r\n"
                        c.print "Content-Length: #{res.body.bytesize}\r\n"
                        c.print "Connection: keep-alive\r\n"
                        res.headers.each { |k, v| c.print "#{k}: #{v}\r\n" }
                        c.print "\r\n#{res.body}"

                        now_log = Time.now.strftime("%d/%b/%Y:%H:%M:%S %z")
                        ip_addr = c.peeraddr[3]

                        $stderr.puts %(#{ip_addr} - - [#{now_log}] "#{method} #{path} #{version}" #{res.status} #{res.body.bytesize})
                        $stderr.puts %(- -> #{path})

                        break if headers['connection'] && headers['connection'].downcase == 'close'
                    end
                rescue EOFError, Errno::ECONNRESET, Errno::EPIPE
                    # Client closed connection normally
                ensure
                    c.close unless c.closed?
                end
            end
        end
    end

    class BridgeServlet < WEBrick::HTTPServlet::AbstractServlet
        @@connections = {}
        @@mutex = Mutex.new

        def get_socket(req,res)
            conn_id = req.path.split("/").last
            conn = @@mutex.synchronize { @@connections[conn_id] }
            if not conn
                $stderr.puts "[#{conn_id}] Connection is not open for #{conn_id}=#{conn}"
                res.status=404
                return nil
            end
            conn
        end

        def close_socket(req,res)
            conn_id = req.path.split("/").last
            conn = @@mutex.synchronize { @@connections.delete(conn_id) }
            return if not conn
            conn.close if not conn.closed?
        end

        def do_POST(req, res)
            conn_id = req.path.split("/").last
            (remote_host,remote_port)=req.body.split(":")
            remote_port=remote_port.to_i
            $stderr.puts "[#{conn_id}] Opening connection to #{remote_host}:#{remote_port} for #{req.peeraddr}..."
            begin
                conn=TCPSocket.open(remote_host,remote_port)
                conn.setsockopt(Socket::SOL_SOCKET, Socket::SO_KEEPALIVE, true)
                @@mutex.synchronize { @@connections[conn_id] = conn }
                $stderr.puts "[#{conn_id}] Connected to #{remote_host}:#{remote_port} #{conn}"
                res.status=201
            rescue
                res['Content-Type'] = "text/plain"
                res.body=$!.message
                $stderr.puts "[#{conn_id}] Connection failed: #$!"
                res.status=406 # Not Acceptable
            end
        end

        def do_PUT(req, res)
            conn_id = req.path.split("/").last
            return if not s=get_socket(req,res)
            begin
                s.print req.body
            rescue Errno::EPIPE, IOError
                $stderr.puts "[#{conn_id}] Connection closed in remote destination (PUT)"
                close_socket(req, res)
                res.status=410 # GONE
            end
        end

        def do_GET(req, res)
            conn_id = req.path.split("/").last
            return if not conn=get_socket(req,res)
            begin
                res.body = conn.read_nonblock(MAXBUF)
            rescue IO::WaitReadable
                begin
                    if IO.select([conn],[],[],READ_TIMEOUT-3)
                        retry
                    else # Timeout
                        res.body = ''
                        res.status=204 # No Content
                    end
                rescue IOError
                    $stderr.puts "[#{conn_id}] Connection closed while waiting (GET)"
                    close_socket(req, res)
                    res.status=410 # Fone
                end
            rescue EOFError, Errno::EPIPE, IOError
                if conn.closed?
                    $stderr.puts "[#{conn_id}] Connection closed by remote destination (GET)"
                else
                    $stderr.puts "[#{conn_id}] Connection closed (GET) #{$!}"
                end
                close_socket(req, res)
                res.status=410 # Gone
            rescue
                $stderr.puts $!.class
            end
        end

        def do_DELETE(req, res)
            conn_id = req.path.split("/").last
            $stderr.puts "[#{conn_id}] Connection closed in client. Trying to close it in remote destination"
            close_socket(req, res)
            res.status=200
        end

    end

    s = WEBrick::HTTPServer.new(
        :Port            => localPort.to_i,
        :RequestTimeout  => 600
    )
    s.mount(location, BridgeServlet)
    trap("INT"){ s.shutdown }
    s.start

else # Client

    require "net/http"
    require 'uri'

    # HACK! https://bugs.ruby-lang.org/issues/12921
    class Net::HTTP
        def proxy_user
          if @proxy_from_env then
            proxy_uri && proxy_uri.user
          else
            @proxy_user
          end
        end
        def proxy_pass
          if @proxy_from_env then
            proxy_uri && proxy_uri.password
          else
            @proxy_pass
          end
        end
    end

    url = URI(url)
    if url.find_proxy
        $stderr.puts "Using proxy: #{url.find_proxy}"
    end

    case localPort
    when "STDIN","-"
        _in=$stdin
        _out=$stdout
        # Keeps this unbuffered
        _in.sync=true
        _out.sync=true
    else
        $stderr.puts "Opening local port #{localPort}"
        local_server = TCPServer.open(localPort.to_i)
        $stderr.puts "Waiting for local connection to port #{localPort}"
        local_server_conn = local_server.accept
        _in=_out=local_server_conn
        # Keep connection alive
        local_server_conn.setsockopt(Socket::SOL_SOCKET, Socket::SO_KEEPALIVE, true)
    end

    #unique Connection IDentifier
    conn_id=`uuidgen`.chomp
    connected=false


    # Open the connection
    begin
        begin
            $stderr.puts "Opening connection over HTTP bridge for #{remote_host}:#{remote_port} (#{conn_id})"
            # HACK! new().start() because of https://bugs.ruby-lang.org/issues/13351
            Net::HTTP.new(url.host, url.port).start do |http|
                error=nil
                res = http.post("#{url.path}/#{conn_id}","#{remote_host}:#{remote_port}")
                if res.kind_of? Net::HTTPCreated
                    connected=true
                else
                    $stderr.puts "The bridge failed to connect to the remote location (#{res}): #{res.body}"
                    connected=false
                    break
                end
            end
        rescue Errno::EPIPE
            $stderr.puts "Connection to bridge #{url} closed"
            retry
        end

        # Not connected, nothing more to do
        exit 1 if not connected

        # Launch Local write/Remote read loop
        Thread.new do
            $stderr.puts "Local write/Remote read loop started"
            begin
                Net::HTTP.new(url.host, url.port).start do |http|
                    http.read_timeout=READ_TIMEOUT+3
                    while connected
                        res = http.get("#{url.path}/#{conn_id}") {|res| _out.print res }
                        if res.kind_of? Net::HTTPGone
                            $stderr.puts "Connection closed in remote location (lw/rr)"
                            connected=false
                            _in.close if not _in.closed?
                            break
                        elsif res.kind_of? Net::HTTPNotFound
                            $stderr.puts "Connection not opened on bridge"
                            connected=false
                            break
                        end
                    end
                end
            rescue Errno::EPIPE
                _in.close if not _in.closed?
            rescue EOFError
                # retry if local connection is still open
                retry if not _in.closed?
                $stderr.puts "Connection to bridge closed (lw/rr)"
            rescue Errno::ECONNREFUSED
                $stderr.puts "Connection to bridge failed (lw/rr)"
                _in.close if not _in.closed?
            rescue Timeout::Error
                $stderr.puts "Timeout (lw/rr)"
                retry if not _in.closed?
            rescue Net::ReadTimeout
                $stderr.puts "Net::ReadTimeout (lw/rr)"
                retry if not _in.closed?
            rescue Net::HTTPServerError
                raise res.message
            end
        end

        # If CTRL+C, SIGHUP or SIGTERM, close _in (and itself)
        trap("INT"){ _in.close }
        trap("SIGHUP"){ _in.close }
        trap("SIGTERM"){ _in.close }

        # Launch "Local read/Remote write loop started"
        $stderr.puts "Local read/Remote write loop started"
        # Keep buffer between retries
        buf=nil
        begin
            Net::HTTP.new(url.host, url.port).start do |http|
                while connected
                    begin
                        # first read from _in ONLY if buf is empty
                        buf=_in.readpartial(MAXBUF) if !buf
                    rescue IO::WaitReadable
                        IO.select([_in])
                        retry
                    rescue EOFError
                        $stderr.puts "Local connection closed (lr/rw)"
                        $stderr.puts "Closing bridge connection to remote location"
                        http.delete("#{url.path}/#{conn_id}")
                        connected=false
                        break
                    end

                    res = http.put("#{url.path}/#{conn_id}",buf)
                    if res.kind_of? Net::HTTPGone
                        $stderr.puts "Connection closed in remote location (lr/rw)"
                        _in.close if not _in.closed?
                        connected=false
                        break
                    end

                    # Buffer sent, clear it
                    buf=nil
                end
            end
        rescue Net::ReadTimeout
            $stderr.puts "Net::ReadTimeout (lr/rw)"
            retry if not _in.closed? and connected
        rescue Net::HTTPServerError
            raise "Server said: '#{res.message}'"
        rescue Errno::EPIPE, IOError
            # retry if local connection is still open
            retry if not _in.closed?
            $stderr.puts "Connection to bridge closed (lr/rw)"
        end
    rescue Errno::ECONNREFUSED
        $stderr.puts "Connection to bridge failed"
    end
end

$stderr.puts "Program Finished!"
